# Generated by Django 3.2.8 on 2023-03-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('code_int', models.IntegerField()),
                ('article', models.CharField(max_length=120)),
                ('tax', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
                ('price_1', models.IntegerField(default=0)),
                ('price_2', models.IntegerField(default=0)),
                ('price_3', models.IntegerField(default=0)),
                ('price_4', models.IntegerField(default=0)),
                ('price_5', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
