# Generated by Django 3.2.8 on 2023-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quanty',
            field=models.IntegerField(default=0),
        ),
    ]
