# Generated by Django 3.2 on 2023-03-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('dv', models.IntegerField()),
                ('name_company', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_opc', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('logo', models.ImageField(default='logo.jpg', upload_to='Logos')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution_Elec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('from_date', models.CharField(max_length=12)),
                ('to_date', models.CharField(max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('document', models.IntegerField()),
                ('users', models.IntegerField()),
                ('to_date', models.CharField(max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
