# Generated by Django 3.2.8 on 2023-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
