# Generated by Django 3.2.8 on 2023-04-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_consecutive_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutive',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='consecutive_ds',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Consecutive_NI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
