# Generated by Django 3.2 on 2023-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('psswd', models.CharField(max_length=20)),
                ('block', models.BooleanField(default=False)),
            ],
        ),
    ]
