# Generated by Django 3.2.8 on 2023-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(default=0),
        ),
    ]
