# Generated by Django 3.2.8 on 2023-03-27 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6)),
                ('number', models.CharField(max_length=100)),
                ('typeDocumentId', models.CharField(max_length=1)),
                ('date', models.CharField(default=datetime.date(2023, 3, 27), max_length=10)),
                ('time', models.CharField(default='10:06:00', max_length=10)),
                ('notes', models.TextField(blank=True, default='Sin Observaciones')),
                ('paymentForm', models.CharField(max_length=1)),
                ('paymentMethods', models.CharField(max_length=2)),
                ('paymentDueDate', models.CharField(default=datetime.date(2023, 3, 27), max_length=10)),
                ('durationMeasure', models.CharField(default=0, max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('quanty', models.CharField(max_length=20)),
                ('ipo', models.CharField(default=0, max_length=10)),
                ('iva', models.CharField(max_length=2)),
                ('discountP', models.CharField(blank=True, default=0, max_length=3, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('state', models.CharField(default='Sin enviar a la DIAN', max_length=60)),
                ('cufe', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reteRenta', models.CharField(default=0, max_length=3)),
                ('client', models.ForeignKey(blank=True, default=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
