# Generated by Django 3.2.8 on 2023-03-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20230327_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discountP',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='durationMeasure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='iva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentForm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentMethods',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quanty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='15:54:42', max_length=10),
        ),
    ]
