# Generated by Django 3.2.8 on 2023-03-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230327_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='iva',
            new_name='tax',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='16:07:54', max_length=10),
        ),
    ]
