# Generated by Django 3.2.8 on 2023-03-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20230327_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_note_applicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cude',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='17:59:22', max_length=10),
        ),
    ]
