# Generated by Django 3.2.8 on 2023-03-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20230327_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attach_document',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='18:52:35', max_length=10),
        ),
    ]
