# Generated by Django 3.2.8 on 2023-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20230328_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='acept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='17:18:43', max_length=10),
        ),
    ]
