# Generated by Django 3.2.8 on 2023-03-30 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20230328_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2023, 3, 30), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentDueDate',
            field=models.CharField(default=datetime.date(2023, 3, 30), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='13:37:11', max_length=10),
        ),
    ]
