# Generated by Django 3.2.8 on 2023-04-01 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20230330_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rejection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2023, 4, 1), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentDueDate',
            field=models.CharField(default=datetime.date(2023, 4, 1), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='11:16:16', max_length=10),
        ),
    ]
