# Generated by Django 3.2.8 on 2023-04-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20230403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='17:52:45', max_length=10),
        ),
    ]
