# Generated by Django 3.2.8 on 2023-04-04 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_invoice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2023, 4, 4), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentDueDate',
            field=models.CharField(default=datetime.date(2023, 4, 4), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='11:51:54', max_length=10),
        ),
    ]
