# Generated by Django 3.2.8 on 2023-04-10 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_invoice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default=datetime.date(2023, 4, 10), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentDueDate',
            field=models.CharField(default=datetime.date(2023, 4, 10), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='09:26:35', max_length=10),
        ),
    ]
