# Generated by Django 3.2.8 on 2023-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_invoice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.CharField(default='11:13:15', max_length=10),
        ),
    ]
